name: CI Main

on: [push, pull_request]

jobs:
  BuildMacOS:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v2
      - name: RunBuild
        run: Source-JUCE/Scripts/macos/build.sh
      - uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: ElectroMap-macOS
          path: Source-JUCE/Scripts/macos/dist


  BuildWindows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: SetupMSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: RunBuild
        shell: cmd
        run: Source-JUCE\Scripts\windows\build.ps1
      - uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: ElectroMap-windows
          path: Source-JUCE/Scripts/windows/dist

